from __future__ import annotations

import json
from pathlib import Path
from typing import Any


REPORT_CASES = ("G15", "Circle", "G16")
REPORT_BERRY_STEP = "0.001"
REPORT_SCALAR_MEMBER = 1


def closed_basis_metrics(summary: dict[str, Any]) -> dict[str, Any]:
    """Extract the report's displayed values from one complete run summary.

    The scalar table intentionally reports the middle M7 member (index 1),
    while the Berry triple retains all three members.  Keeping that choice in
    code prevents hand-copied report numbers from silently drifting.
    """

    metrics: dict[str, Any] = {}
    for case in REPORT_CASES:
        record = summary["cases"][case]
        step = record["berry_steps"][REPORT_BERRY_STEP]
        member = step["member_summaries"][REPORT_SCALAR_MEMBER]
        scalar = record["scalar_c3_residual_grid32"]
        metrics[case] = {
            "scalar": {
                "H": scalar["H"][REPORT_SCALAR_MEMBER],
                "E": scalar["E"][REPORT_SCALAR_MEMBER],
                "energy": scalar["energy"][REPORT_SCALAR_MEMBER],
                "composite_23": scalar["composite_23"],
            },
            "berry": step["pairwise_c3_residual"]["rank2_phase_density_relative_residual"],
            "triple": [item["phase_density_rank2"] for item in step["member_summaries"]],
            "link": min(item["association"]["rank2"]["min_singular_value"] for item in step["member_summaries"]),
            "scalar_member": member["member"],
        }
    return metrics


def render_closed_basis_numeric_appendix(metrics: dict[str, Any], *, source_record: str) -> str:
    """Render a compact, machine-generated numeric appendix for the report."""

    lines = [
        "<!-- Generated by legumephc.reporting; do not hand-edit numeric values. -->",
        f"Machine-checked numeric appendix (source summary: `{source_record}`, Berry step `{REPORT_BERRY_STEP}`, scalar member index `{REPORT_SCALAR_MEMBER}`):",
        "",
        "| case | H | E | energy | composite [2,3] H | Berry rank-2 residual | min link singular value |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for case in REPORT_CASES:
        item = metrics[case]
        scalar = item["scalar"]
        lines.append(
            f"| {case} | {scalar['H']:.3e} | {scalar['E']:.3e} | {scalar['energy']:.3e} | "
            f"{scalar['composite_23']:.3e} | {item['berry']:.3e} | {item['link']:.6f} |"
        )
    lines.extend([
        "",
        "Berry phase-density triples (members 0, 1, 2):",
    ])
    for case in REPORT_CASES:
        triple = ", ".join(f"{value:.6f}" for value in metrics[case]["triple"])
        lines.append(f"- {case}: `({triple})`")
    return "\n".join(lines) + "\n"


def validate_closed_basis_report(report_text: str, metrics: dict[str, Any]) -> list[str]:
    """Return generated numeric tokens missing from a checked-in report."""

    expected = render_closed_basis_numeric_appendix(metrics, source_record="<source-summary>")
    missing: list[str] = []
    for line in expected.splitlines():
        if line.startswith("<!--") or line.startswith("|") or line.startswith("Berry phase") or line.startswith("- "):
            if line not in report_text:
                missing.append(line)
    return missing


def load_summary(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))
